import { isTauri } from "@tauri-apps/api/core";
import { open } from "@tauri-apps/plugin-dialog";
import { useEffect, useMemo, useState } from "react";

import adultMascot from "../../../../img/azulclaw.png";
import babyMascot from "../../../../img/hatching_azulclaw.png";

import { Tooltip } from "../../components/Tooltip";
import { saveHatching } from "../../lib/api";
import type { HatchingProfile } from "../../lib/contracts";
import { defaultHatchingProfile } from "../../lib/mock-data";

interface HatchingShellProps {
  profile?: HatchingProfile;
  onboardingRequired?: boolean;
  onProfileSaved?: (profile: HatchingProfile) => void;
}

type StepType = "text" | "textarea" | "skills" | "path";
type NavDir = "forward" | "back";
type SkillFieldType = "text" | "password" | "url";

interface WizardQuestion {
  id: string;
  title: string;
  helper: string;
  placeholder: string;
  type: StepType;
  emoji: string;
}

interface SkillField {
  id: string;
  label: string;
  helper: string;
  placeholder: string;
  type: SkillFieldType;
}

interface SkillDefinition {
  id: string;
  title: string;
  description: string;
  fields: SkillField[];
}

interface WizardState {
  answers: string[];
  configuredSkills: string[];
  skillConfigs: Record<string, Record<string, string>>;
  workspaceRoot: string;
  confirmSensitiveActions: boolean;
}

const wizardQuestions: WizardQuestion[] = [
  { id: "NAME", title: "What do you want to call your AzulClaw?", helper: "That will be its name in the app. You can change it whenever you like.", placeholder: "AzulClaw, Atlas, Clawy...", type: "text", emoji: "Paw" },
  { id: "ROLE", title: "What do you want it to be for you?", helper: "Answer freely. There is no wrong answer.", placeholder: "I want you to be my technical assistant for organising tasks, code and decisions.", type: "textarea", emoji: "Role" },
  { id: "MISSION", title: "What should its main mission be?", helper: "This defines where it should focus when working with you.", placeholder: "Help me move forward with focus, context and order.", type: "textarea", emoji: "Mission" },
  { id: "CHARACTER", title: "How do you want it to talk and act?", helper: "Describe its tone, style and how much autonomy you want to give it.", placeholder: "Direct, clear, technical and proactive, but confirm sensitive actions.", type: "textarea", emoji: "Tone" },
  { id: "CAPABILITIES", title: "Which skills do you want to activate first?", helper: "Click a skill to configure it. It will only activate once you fully complete that popup.", placeholder: "", type: "skills", emoji: "Skills" },
  { id: "WORKSPACE", title: "Which folder will be its workspace?", helper: "The workspace must be a folder. It will be AzulClaw's desk: its safe zone for reading, writing and organising files.", placeholder: "C:\\Users\\user\\Desktop\\AzulWorkspace", type: "path", emoji: "Desk" },
];

const SKILL_CATALOG: SkillDefinition[] = [
  {
    id: "Email",
    title: "Email",
    description: "Read and prepare emails from a connected account.",
    fields: [
      { id: "provider", label: "Provider", helper: "Example: Gmail or Outlook.", placeholder: "Gmail", type: "text" },
      { id: "email", label: "Email address", helper: "Main address AzulClaw will use.", placeholder: "you@domain.com", type: "text" },
      { id: "token", label: "Token or app password", helper: "Credential needed to authenticate access.", placeholder: "Paste your credential here", type: "password" },
    ],
  },
  {
    id: "Telegram",
    title: "Telegram",
    description: "Send notifications and operate through a bot.",
    fields: [
      { id: "botToken", label: "Bot token", helper: "Token generated by BotFather.", placeholder: "123456:ABC...", type: "password" },
      { id: "chatId", label: "Chat ID", helper: "Chat or user authorised to talk with AzulClaw.", placeholder: "987654321", type: "text" },
    ],
  },
  {
    id: "Slack",
    title: "Slack",
    description: "Post messages and handle events in work channels.",
    fields: [
      { id: "workspaceUrl", label: "Workspace URL", helper: "Workspace base URL.", placeholder: "https://my-team.slack.com", type: "url" },
      { id: "botToken", label: "Bot token", helper: "Bot token with the required permissions.", placeholder: "xoxb-...", type: "password" },
      { id: "defaultChannel", label: "Default channel", helper: "Main channel where it can write.", placeholder: "#azulclaw", type: "text" },
    ],
  },
  {
    id: "Alexa",
    title: "Alexa",
    description: "Connect voice actions and home routines.",
    fields: [
      { id: "skillId", label: "Skill ID", helper: "Skill or integration identifier.", placeholder: "amzn1.ask.skill...", type: "text" },
      { id: "clientSecret", label: "Client secret", helper: "Credential used to validate requests.", placeholder: "Paste your secret here", type: "password" },
    ],
  },
  {
    id: "Memory",
    title: "Memory",
    description: "Save relevant context and retrieve it when needed.",
    fields: [
      { id: "retentionPolicy", label: "Retention policy", helper: "How much and how to remember.", placeholder: "Preferences and technical context", type: "text" },
      { id: "memoryScope", label: "Initial scope", helper: "What type of information it can memorise.", placeholder: "Projects, decisions and preferences", type: "text" },
    ],
  },
];

const SKILL_IDS = new Set(SKILL_CATALOG.map((skill) => skill.id));

function buildTextAnswers(profile: HatchingProfile) {
  return [profile.name, profile.role, profile.mission, [profile.tone, profile.style, profile.autonomy].filter(Boolean).join(", ")];
}

function buildWizardState(profile: HatchingProfile, onboardingRequired: boolean): WizardState {
  return {
    answers: buildTextAnswers(profile),
    configuredSkills: onboardingRequired ? [] : profile.skills.filter((skill) => SKILL_IDS.has(skill)),
    skillConfigs: onboardingRequired ? {} : profile.skill_configs,
    workspaceRoot: profile.workspace_root,
    confirmSensitiveActions: profile.confirm_sensitive_actions,
  };
}



function deriveTone(value: string, fallback: string) {
  const v = value.toLowerCase();
  if (v.includes("serious") || v.includes("formal")) return "Serious";
  if (v.includes("warm") || v.includes("friendly") || v.includes("casual")) return "Warm";
  if (v.includes("direct") || v.includes("clear") || v.includes("concise")) return "Direct";
  return fallback || "Direct";
}

function deriveStyle(value: string, fallback: string) {
  const v = value.toLowerCase();
  if (v.includes("brief") || v.includes("short") || v.includes("concise")) return "Brief";
  if (v.includes("technical") || v.includes("deep") || v.includes("detailed")) return "Technical";
  if (v.includes("explain") || v.includes("detail") || v.includes("thorough")) return "Explanatory";
  return fallback || "Explanatory";
}

function deriveAutonomy(value: string, fallback: string) {
  const v = value.toLowerCase();
  if (v.includes("confirm") || v.includes("ask") || v.includes("cautious") || v.includes("check")) return "Confirmatory";
  if (v.includes("autonomo") || v.includes("autonomous") || v.includes("initiative") || v.includes("proactive")) return "High autonomy";
  return fallback || "Moderately autonomous";
}

function buildProfileFromWizard(base: HatchingProfile, state: WizardState): HatchingProfile {
  const [name, role, mission, temper] = state.answers;
  return {
    ...base,
    name: name.trim() || base.name,
    role: role.trim() || base.role,
    mission: mission.trim() || base.mission,
    tone: deriveTone(temper, base.tone),
    style: deriveStyle(temper, base.style),
    autonomy: deriveAutonomy(temper, base.autonomy),

    workspace_root: state.workspaceRoot.trim() || base.workspace_root,
    confirm_sensitive_actions: state.confirmSensitiveActions,
    skills: state.configuredSkills,
    skill_configs: state.skillConfigs,
  };
}

function getStepEmoji(label: string) {
  return label;
}

export function HatchingShell({
  profile: incomingProfile,
  onboardingRequired = false,
  onProfileSaved,
}: HatchingShellProps) {
  const initial = incomingProfile ?? defaultHatchingProfile;
  const initialState = buildWizardState(initial, onboardingRequired);

  const [profile, setProfile] = useState<HatchingProfile>(initial);
  const [answers, setAnswers] = useState<string[]>(initialState.answers);
  const [configuredSkills, setConfiguredSkills] = useState<string[]>(initialState.configuredSkills);
  const [skillConfigs, setSkillConfigs] = useState<Record<string, Record<string, string>>>(initialState.skillConfigs);
  const [workspaceRoot, setWorkspaceRoot] = useState(initialState.workspaceRoot);
  const [confirmSensitiveActions, setConfirmSensitiveActions] = useState(initialState.confirmSensitiveActions);
  const [currentStep, setCurrentStep] = useState(0);
  const [isSaving, setIsSaving] = useState(false);
  const [isExiting, setIsExiting] = useState(false);
  const [navDir, setNavDir] = useState<NavDir>("forward");
  const [isPickingWorkspace, setIsPickingWorkspace] = useState(false);
  const [workspacePickerError, setWorkspacePickerError] = useState("");
  const [activeSkillId, setActiveSkillId] = useState<string | null>(null);
  const [skillDraft, setSkillDraft] = useState<Record<string, string>>({});
  const [skillModalError, setSkillModalError] = useState("");

  useEffect(() => {
    if (!incomingProfile) return;
    const nextState = buildWizardState(incomingProfile, onboardingRequired);
    setProfile(incomingProfile);
    setAnswers(nextState.answers);
    setConfiguredSkills(nextState.configuredSkills);
    setSkillConfigs(nextState.skillConfigs);
    setWorkspaceRoot(nextState.workspaceRoot);
    setConfirmSensitiveActions(nextState.confirmSensitiveActions);
  }, [incomingProfile, onboardingRequired]);

  const draftProfile = useMemo(
    () => buildProfileFromWizard(profile, { answers, configuredSkills, skillConfigs, workspaceRoot, confirmSensitiveActions }),
    [answers, configuredSkills, confirmSensitiveActions, profile, skillConfigs, workspaceRoot],
  );

  const isFinalStep = currentStep === wizardQuestions.length;
  const activeQuestion = wizardQuestions[currentStep];
  const stepNumber = Math.min(currentStep + 1, wizardQuestions.length);
  const mascotImage = onboardingRequired && !draftProfile.is_hatched ? babyMascot : adultMascot;
  const activeSkill = activeSkillId ? SKILL_CATALOG.find((skill) => skill.id === activeSkillId) ?? null : null;

  function navigate(toStep: number, dir: NavDir) {
    if (isExiting || activeSkill) return;
    setNavDir(dir);
    setIsExiting(true);
    setTimeout(() => {
      setCurrentStep(toStep);
      setIsExiting(false);
    }, 260);
  }

  function handleNext() {
    navigate(Math.min(currentStep + 1, wizardQuestions.length), "forward");
  }

  function handleBack() {
    navigate(Math.max(currentStep - 1, 0), "back");
  }

  useEffect(() => {
    function onKey(event: KeyboardEvent) {
      if (event.key !== "Enter" || event.shiftKey || isExiting || isFinalStep || activeSkill) return;
      const target = event.target as HTMLElement | null;
      if (!target || target.tagName === "TEXTAREA" || target.tagName === "BUTTON") return;
      event.preventDefault();
      handleNext();
    }

    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [activeSkill, isExiting, isFinalStep, currentStep]);

  function handleAnswerChange(value: string) {
    setAnswers((current) => current.map((item, index) => (index === currentStep ? value : item)));
  }

  function openSkillConfig(skillId: string) {
    setActiveSkillId(skillId);
    setSkillDraft(skillConfigs[skillId] ?? {});
    setSkillModalError("");
  }

  function closeSkillConfig() {
    setActiveSkillId(null);
    setSkillDraft({});
    setSkillModalError("");
  }

  function handleSkillFieldChange(fieldId: string, value: string) {
    setSkillDraft((current) => ({ ...current, [fieldId]: value }));
  }

  function saveSkillConfig() {
    if (!activeSkill) return;
    const missingField = activeSkill.fields.find((field) => !skillDraft[field.id]?.trim());
    if (missingField) {
      setSkillModalError(`Please complete "${missingField.label}".`);
      return;
    }

    setSkillConfigs((current) => ({ ...current, [activeSkill.id]: skillDraft }));
    setConfiguredSkills((current) => (current.includes(activeSkill.id) ? current : [...current, activeSkill.id]));
    closeSkillConfig();
  }

  function deactivateSkill(skillId: string) {
    setConfiguredSkills((current) => current.filter((item) => item !== skillId));
    setSkillConfigs((current) => {
      const next = { ...current };
      delete next[skillId];
      return next;
    });
    closeSkillConfig();
  }

  async function handlePickWorkspace() {
    setWorkspacePickerError("");
    if (!isTauri()) {
      setWorkspacePickerError("The native selector is only available inside the Tauri desktop app.");
      return;
    }

    setIsPickingWorkspace(true);
    try {
      const selected = await open({
        directory: true,
        multiple: false,
        defaultPath: workspaceRoot || undefined,
        title: "Select the AzulClaw workspace folder",
      });
      if (typeof selected === "string" && selected.trim()) setWorkspaceRoot(selected);
    } catch (error) {
      const detail = error instanceof Error ? error.message : String(error);
      console.error("Workspace picker failed", error);
      setWorkspacePickerError(`Could not open the native selector. ${detail}`);
    } finally {
      setIsPickingWorkspace(false);
    }
  }

  async function handleSave(markAsHatched: boolean) {
    setIsSaving(true);
    const saved = await saveHatching({ ...draftProfile, is_hatched: markAsHatched || profile.is_hatched });
    const nextState = buildWizardState(saved, false);
    setProfile(saved);
    setAnswers(nextState.answers);
    setConfiguredSkills(nextState.configuredSkills);
    setSkillConfigs(nextState.skillConfigs);
    setWorkspaceRoot(nextState.workspaceRoot);
    setConfirmSensitiveActions(nextState.confirmSensitiveActions);
    onProfileSaved?.(saved);
    setIsSaving(false);
  }

  const contentAnim = isExiting
    ? navDir === "forward" ? "hw-exit-fwd" : "hw-exit-back"
    : navDir === "forward" ? "hw-enter-fwd" : "hw-enter-back";

  const shellClass = onboardingRequired ? "hw-fullscreen" : "hw-contained card";
  const nextButtonLabel = activeQuestion?.type === "skills" && configuredSkills.length === 0 ? "Skip for now ->" : "Next ->";
  const nextHint = activeQuestion?.type === "skills" && configuredSkills.length === 0 ? "Press Enter to skip for now" : "Press Enter to continue";

  if (!onboardingRequired) {
    return (
      <section className="single-panel-layout">
        <div className="card panel-stack">
          <div className="panel-heading" style={{ borderBottom: "1px solid var(--line)", paddingBottom: "20px", marginBottom: "4px" }}>
            <div>
              <p className="eyebrow">Identity</p>
              <h2>Hatching profile</h2>
              <p className="hint-text" style={{ margin: "4px 0 0" }}>Adjust your agent's core personality and environment at any time.</p>
            </div>
            <button type="button" className="primary-button" onClick={() => void handleSave(true)} disabled={isSaving}>
              {isSaving ? "Saving..." : "Apply changes"}
            </button>
          </div>

          <div className="two-column-grid">
            <label className="form-field">
              <span>Agent name</span>
              <input
                type="text"
                value={answers[0] ?? ""}
                onChange={(e) => setAnswers(c => { const n = [...c]; n[0] = e.target.value; return n; })}
              />
            </label>
            <label className="form-field">
              <span>Behaviour and tone</span>
              <input
                type="text"
                value={answers[3] ?? ""}
                onChange={(e) => setAnswers(c => { const n = [...c]; n[3] = e.target.value; return n; })}
              />
            </label>
          </div>

          <div className="two-column-grid">
            <label className="form-field">
              <span>Main role</span>
              <textarea
                rows={4}
                value={answers[1] ?? ""}
                onChange={(e) => setAnswers(c => { const n = [...c]; n[1] = e.target.value; return n; })}
              />
            </label>
            <label className="form-field">
              <span>Mission or goal</span>
              <textarea
                rows={4}
                value={answers[2] ?? ""}
                onChange={(e) => setAnswers(c => { const n = [...c]; n[2] = e.target.value; return n; })}
              />
            </label>
          </div>

          <div className="subcard form-section">
            <p className="eyebrow">Secure workspace</p>
            <div style={{ display: "flex", gap: "12px", alignItems: "center" }}>
              <Tooltip text={workspaceRoot} className="workspace-banner-path">
                {workspaceRoot}
              </Tooltip>
              <button type="button" className="ghost-button" onClick={() => void handlePickWorkspace()}>
                Choose folder
              </button>
            </div>
            <label className="form-field" style={{ marginTop: "8px" }}>
              <span>Path</span>
              <input
                type="text"
                value={workspaceRoot}
                onChange={(e) => setWorkspaceRoot(e.target.value)}
                style={{ fontFamily: "ui-monospace, monospace", fontSize: "0.85rem" }}
              />
            </label>
            {workspacePickerError && <p style={{ margin: 0, color: "#fca5a5", fontSize: "0.85rem" }}>{workspacePickerError}</p>}

            <div style={{ marginTop: "8px" }}>
              <p className="eyebrow" style={{ marginBottom: "10px" }}>Sensitive action confirmation</p>
              <div className="filter-row">
                <button type="button" className={confirmSensitiveActions ? "primary-button" : "ghost-button"} onClick={() => setConfirmSensitiveActions(true)}>
                  Ask before acting
                </button>
                <button type="button" className={!confirmSensitiveActions ? "primary-button" : "ghost-button"} onClick={() => setConfirmSensitiveActions(false)}>
                  Full autonomy
                </button>
              </div>
            </div>
          </div>
        </div>
      </section>
    );
  }

  return (
    <div className={shellClass}>
      <header className="hw-header">
        <div className="hw-brand">
          <img className="hw-mascot" src={mascotImage} alt="AzulClaw" />
          <div>
            <p className="hw-eyebrow">Hatching</p>
            <h2 className="hw-brand-title">{onboardingRequired ? "Create your AzulClaw" : "Reconfigure your AzulClaw"}</h2>
          </div>
        </div>
        <div className="hw-dots" aria-label={`Step ${stepNumber} of ${wizardQuestions.length}`}>
          {wizardQuestions.map((_, index) => (
            <span key={index} className={`hw-dot${index < currentStep ? " hw-dot-done" : index === currentStep ? " hw-dot-active" : ""}`} />
          ))}
        </div>
      </header>

      <div className="hw-progress" role="progressbar">
        <span style={{ width: `${(currentStep / wizardQuestions.length) * 100}%` }} />
      </div>

      <main className="hw-main">
        {!isFinalStep ? (
          <div key={currentStep} className={`hw-content ${contentAnim}`}>
            <div className="hw-question">
              <span className="hw-emoji">{getStepEmoji(activeQuestion.emoji)}</span>
              <p className="hw-label">{activeQuestion.id}</p>
              <h1 className="hw-title">{activeQuestion.title}</h1>
              <p className="hw-helper">{activeQuestion.helper}</p>
            </div>

            <div className="hw-answer-wrap">
              {activeQuestion.type === "text" && (
                <input id={`hw-answer-${currentStep}`} className="hw-input-line" type="text" value={answers[currentStep] ?? ""} placeholder={activeQuestion.placeholder} onChange={(event) => handleAnswerChange(event.target.value)} autoFocus />
              )}

              {activeQuestion.type === "textarea" && (
                <textarea id={`hw-answer-${currentStep}`} className="hw-textarea" value={answers[currentStep] ?? ""} placeholder={activeQuestion.placeholder} onChange={(event) => handleAnswerChange(event.target.value)} autoFocus />
              )}

              {activeQuestion.type === "skills" && (
                <div className="hw-skills-wrap">
                  <div className="hw-skills-copy">
                    <p className="hw-inline-note">Here you don't type free text. You can only activate skills from the available catalogue.</p>
                    <p className="hw-inline-note">Clicking a skill opens its configuration. It won't be activated until you complete that popup.</p>
                  </div>

                  <div className="hw-skills-grid">
                    {SKILL_CATALOG.map((skill) => {
                      const isConfigured = configuredSkills.includes(skill.id);
                      return (
                        <button key={skill.id} type="button" className={`hw-skill-card${isConfigured ? " hw-skill-card-active" : ""}`} onClick={() => openSkillConfig(skill.id)}>
                          <div className="hw-skill-card-top">
                            <span className="hw-skill-card-title">{skill.title}</span>
                            <span className={`hw-skill-state${isConfigured ? " hw-skill-state-ready" : ""}`}>{isConfigured ? "Configured" : "Configure"}</span>
                          </div>
                          <p className="hw-skill-card-body">{skill.description}</p>
                        </button>
                      );
                    })}
                  </div>

                  <div className="hw-skill-summary">
                    <span className="hw-field-label">Currently active skills</span>
                    <div className="hw-skill-tags">
                      {configuredSkills.length > 0 ? configuredSkills.map((skill) => <span key={skill} className="hw-skill-tag">{skill}</span>) : <span className="hw-inline-note">None for now.</span>}
                    </div>
                  </div>

                  <p className="hw-inline-note">If you don't want to activate any yet, continue with Skip for now.</p>
                </div>
              )}

              {activeQuestion.type === "path" && (
                <div className="hw-workspace-wrap">
                  <div className="hw-workspace-panel">
                    <p className="hw-inline-note">Think of it as AzulClaw's desk. Everything it reads, creates or organises will live inside that folder.</p>

                    <div className="hw-workspace-actions">
                      <button type="button" className="hw-btn-ghost" onClick={() => void handlePickWorkspace()} disabled={isPickingWorkspace}>
                        {isPickingWorkspace ? "Opening browser..." : "Choose folder..."}
                      </button>
                      <span className="hw-inline-note">You can also paste or adjust the path manually.</span>
                    </div>

                    <label className="hw-field-label" htmlFor="hw-workspace-root">Workspace folder</label>
                    <input id="hw-workspace-root" className="hw-input-line hw-input-mono" type="text" value={workspaceRoot} placeholder={activeQuestion.placeholder} onChange={(event) => setWorkspaceRoot(event.target.value)} autoFocus />

                    {workspacePickerError && <p className="hw-inline-note hw-inline-note-warning">{workspacePickerError}</p>}

                    <div className="hw-workspace-confirm">
                      <p className="hw-field-label">Sensitive actions</p>
                      <div className="hw-choice-row">
                        <button type="button" className={`hw-choice${confirmSensitiveActions ? " hw-choice-active" : ""}`} onClick={() => setConfirmSensitiveActions(true)}>
                          Ask before changing important things
                        </button>
                        <button type="button" className={`hw-choice${!confirmSensitiveActions ? " hw-choice-active" : ""}`} onClick={() => setConfirmSensitiveActions(false)}>
                          Let it act without prior confirmation
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              )}
            </div>

            {activeQuestion.type !== "textarea" && (
              <p className="hw-hint">
                <span>{nextHint}</span>
                <kbd className="hw-kbd">Enter</kbd>
              </p>
            )}
          </div>
        ) : (
          <div key="final" className={`hw-content hw-celebrate ${contentAnim}`}>
            <img src={mascotImage} alt="AzulClaw" className="hw-celebrate-img" />
            <div className="hw-question" style={{ textAlign: "center" }}>
              <p className="hw-label">READY</p>
              <h1 className="hw-title">{draftProfile.name} is ready to get started</h1>
              <p className="hw-helper">This is the starting point. Everything can be adjusted later from Settings.</p>
            </div>

            <div className="hw-summary-grid">
              <div className="hw-summary-item"><span className="hw-summary-label">Name</span><span className="hw-summary-value">{draftProfile.name}</span></div>

              <div className="hw-summary-item"><span className="hw-summary-label">Style</span><span className="hw-summary-value">{draftProfile.tone} · {draftProfile.style}</span></div>
              <div className="hw-summary-item"><span className="hw-summary-label">Workspace</span><span className="hw-summary-value hw-mono">{draftProfile.workspace_root}</span></div>
              <div className="hw-summary-item" style={{ gridColumn: "1 / -1" }}><span className="hw-summary-label">Capabilities</span><span className="hw-summary-value">{draftProfile.skills.length > 0 ? draftProfile.skills.join(", ") : "None for now"}</span></div>
            </div>
          </div>
        )}
      </main>

      <footer className="hw-footer">
        <button type="button" className="hw-btn-ghost" onClick={handleBack} disabled={currentStep === 0 || Boolean(activeSkill)}>Back</button>
        <span className="hw-step-label">{isFinalStep ? "Summary" : `${stepNumber} / ${wizardQuestions.length}`}</span>

        {isFinalStep ? (
          <div style={{ display: "flex", gap: "10px" }}>
            {!onboardingRequired && <button type="button" className="hw-btn-ghost" onClick={() => void handleSave(false)}>{isSaving ? "Saving..." : "Save draft"}</button>}
            <button type="button" className="hw-btn-primary" onClick={() => void handleSave(true)}>
              {isSaving ? "Saving..." : onboardingRequired ? "Enter the desktop ->" : "Apply changes ->"}
            </button>
          </div>
        ) : (
          <button type="button" className="hw-btn-primary" onClick={handleNext} disabled={Boolean(activeSkill)}>{nextButtonLabel}</button>
        )}
      </footer>

      {activeSkill && (
        <div className="hw-modal-backdrop" onClick={closeSkillConfig}>
          <section className="hw-modal-card" role="dialog" aria-modal="true" aria-labelledby="hw-skill-modal-title" onClick={(event) => event.stopPropagation()}>
            <div className="hw-modal-head">
              <div>
                <p className="hw-label">CONFIGURE SKILL</p>
                <h3 id="hw-skill-modal-title" className="hw-modal-title">{activeSkill.title}</h3>
              </div>
              <button type="button" className="hw-btn-ghost" onClick={closeSkillConfig}>Close</button>
            </div>

            <p className="hw-inline-note">{activeSkill.description}</p>

            <div className="hw-modal-fields">
              {activeSkill.fields.map((field, index) => (
                <label key={field.id} className="hw-modal-field">
                  <span className="hw-field-label">{field.label}</span>
                  <input className="hw-modal-input" type={field.type} value={skillDraft[field.id] ?? ""} placeholder={field.placeholder} onChange={(event) => handleSkillFieldChange(field.id, event.target.value)} autoFocus={index === 0} />
                  <span className="hw-inline-note">{field.helper}</span>
                </label>
              ))}
            </div>

            {skillModalError && <p className="hw-inline-note hw-inline-note-warning">{skillModalError}</p>}

            <div className="hw-modal-actions">
              {configuredSkills.includes(activeSkill.id) && <button type="button" className="hw-btn-ghost" onClick={() => deactivateSkill(activeSkill.id)}>Deactivate skill</button>}
              <button type="button" className="hw-btn-primary" onClick={saveSkillConfig}>{configuredSkills.includes(activeSkill.id) ? "Save configuration" : "Activate skill"}</button>
            </div>
          </section>
        </div>
      )}
    </div>
  );
}
